name: 'Release'

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest 
    if: github.ref == 'refs/heads/master'

    steps:
      
      - name: Get latest run ID
        id: runid
        run: |
          run_id=$(curl --request GET \
            --url https://api.github.com/repos/${{ github.repository }}/actions/workflows/build.yml/runs \
            --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
            | jq '.workflow_runs[] | select(.status=="completed") | .id' | head -1)
          echo "::set-output name=run-id::$run_id"

      - name: ⬇️ Download binary output from build.yml
        uses: actions/download-artifact@v4
        with:
          name: bin
          path: bin
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ steps.runid.outputs.run-id }}

      - name: ⬇️ Download floor from build.yml
        uses: actions/download-artifact@v4
        with:
          pattern: floor-*
          path: floor
          merge-multiple: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ steps.runid.outputs.run-id }}

      - name: 🔍 view artifacts to be used
        run: ls -R
        working-directory: .

      - name: 🔢 prep environment
        run: |
          echo "VERSION=$(cat bin/version.txt)" >> "$GITHUB_ENV"
          grep -m 2 -B 1000 '^## ' bin/release-history.md | tail -n +3 | head -n -2 > release-notes.md
          cat release-notes.md

      - name: 📦 Publish to NuGet
        run: dotnet nuget push bin/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate

      # https://github.com/softprops/action-gh-release
      - name: 📢 Create release
        uses: softprops/action-gh-release@v1
        if: github.ref == 'refs/heads/master'
        with:
          tag_name: ${{ env.VERSION }}
          name: ${{ env.VERSION }}
          files: |
            bin/*.nupkg
            floor/*.zip
          body_path: release-notes.md
